name: bubble
description: Speech bubble
version: 0.0.1
author: Victor Dunaev <victor.dunaev@gmail.com>
homepage: https://github.com/vi-k

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
